---
sidebar: sidebar 
permalink: reference_legal_notices.html 
keywords: copyrights, notice, trademarks, patents, privacy, open source 
summary: Rechtliche Hinweise ermöglichen den Zugriff auf Copyright-Erklärungen, Marken, Patente und mehr. 
---
= Rechtliche Hinweise
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Rechtliche Hinweise ermöglichen den Zugriff auf Copyright-Erklärungen, Marken, Patente und mehr.



== Urheberrecht

http://[]



== Marken

NetApp, das NETAPP Logo und die auf der NetApp Markenseite aufgeführten Marken sind Marken von NetApp Inc. Andere Firmen- und Produktnamen können Marken der jeweiligen Eigentümer sein.

http://[]



== Patente

Eine aktuelle Liste der NetApp Patente finden Sie unter:

https://[]



== Datenschutzrichtlinie

https://[]



== Open Source

In den Benachrichtigungsdateien finden Sie Informationen zu Urheberrechten und Lizenzen von Drittanbietern, die in der NetApp Software verwendet werden.

* link:media/notice_cloud_manager_3.6.6.pdf["Hinweis zu OnCommand Cloud Manager 3.6.6"^]
* link:media/notice_cloud_manager_3.6.1.pdf["Hinweis zu OnCommand Cloud Manager 3.6.1"^]
* link:media/notice_cloud_manager_3.6.pdf["Hinweis zu OnCommand Cloud Manager 3.6"^]

