---
sidebar: sidebar 
permalink: reference_additional_info.html 
keywords: community, forums, help, support, videos, policies, json, api, ontap, release notes, bugs, limitations, known issues, permissions, apis 
summary: Über verschiedene Ressourcen, darunter Videos, Foren und Support, erhalten Sie Hilfe und weitere Informationen zu Cloud Manager und Cloud Volumes ONTAP. 
---
= Wo Sie Hilfe und weitere Informationen erhalten
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Über verschiedene Ressourcen, darunter Videos, Foren und Support, erhalten Sie Hilfe und weitere Informationen zu Cloud Manager und Cloud Volumes ONTAP.

* https://["Videos für Cloud Manager und Cloud Volumes ONTAP"^]
+
Sehen Sie sich Videos an, die Ihnen zeigen, wie Sie Cloud Volumes ONTAP in AWS und Azure implementieren und managen und wie Sie Daten in Ihrer Hybrid Cloud replizieren können.

* http://["Richtlinien für Cloud Manager"^]
+
Laden Sie JSON-Dateien herunter, die die Berechtigungen enthalten, die Cloud Manager zum Ausführen von Aktionen in AWS und Azure benötigt.

* link:api.html["Cloud Manager API-Entwicklerleitfaden"^]
+
Lesen Sie einen Überblick über die APIs, Beispiele für deren Verwendung und eine API-Referenz.

* Training für Cloud Volumes ONTAP
+
** https://["Grundlagen von Cloud Volumes ONTAP"^]
** https://["Implementierung und Management von Cloud Volumes ONTAP für Azure"^]


* Technische Berichte
+
** https://["NetApp Technical Report 4383: Performance Characterization of Cloud Volumes ONTAP in Amazon Web Services with Application Workloads"^]
** https://["Technischer Bericht von NetApp 4671: Performance-Charakterisierung von Cloud Volumes ONTAP in Azure mit Applikations-Workloads"^]


* https://["Cloud Volumes ONTAP 9 SVM Disaster Recovery Preparation Express-Leitfaden"^]
+
Beschreibt, wie eine Ziel-SVM zur Vorbereitung auf die Disaster Recovery schnell konfiguriert wird.

* https://["Cloud Volumes ONTAP 9 SVM Disaster Recovery Express Guide"^]
+
Beschreibt, wie Sie eine Ziel-SVM nach einem Notfall schnell aktivieren und dann die Quell-SVM erneut aktivieren.

* http://["ONTAP 9 Dokumentationszentrum"^]
+
Greifen Sie auf die Produktdokumentation für ONTAP zu, die Ihnen bei der Verwendung von Cloud Volumes ONTAP helfen kann.

* https://["NetApp Cloud Volumes ONTAP Support"^]
+
Greifen Sie auf Support-Ressourcen zu, um Hilfe zu erhalten und Probleme mit Cloud Volumes ONTAP zu beheben.

* https://["NetApp Community: Cloud Data Services"^]
+
Tauschen Sie sich mit Kollegen aus, stellen Sie Fragen, tauschen Sie Ideen aus, suchen Sie nach Ressourcen und tauschen Sie Best Practices aus.

* http://["NetApp Cloud Central"^]
+
Hier finden Sie weitere Informationen zu NetApp Produkten und Lösungen für die Cloud.

* http://["NetApp Produktdokumentation"^]
+
In der NetApp Produktdokumentation finden Sie Anleitungen, Ressourcen und Antworten.


