---
sidebar: sidebar 
permalink: reference_default_configs.html 
keywords: linux, user name, operating system, installation files, installation folder, folder, log, logs, service, mysql, packages, linux,  svm, LIF, LIFs, configuration backups, attributes, autosize, security style, space guarantee, unix permissions, NTFS, UNIX, boot, root, disks, aggr0, aggr1, svm, svms, storage virtual machine, LIF failover, failover, attributes, volume attributes, boot disk, root disk 
summary: Details zur Konfiguration von Cloud Manager und Cloud Volumes ONTAP können Ihnen bei der Administration der Systeme helfen. 
---
= Standardkonfigurationen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Details zur Konfiguration von Cloud Manager und Cloud Volumes ONTAP können Ihnen bei der Administration der Systeme helfen.



== Standardkonfiguration für Cloud Manager unter Linux

Wenn Sie eine Fehlerbehebung für Cloud Manager oder Ihren Linux-Host durchführen müssen, kann dies dazu beitragen, die Konfiguration von Cloud Manager zu verstehen.

* Wenn Sie Cloud Manager über NetApp Cloud Central (oder direkt über den AWS Marketplace oder Azure Marketplace) bereitgestellt haben, beachten Sie Folgendes:
+
** In AWS lautet der Benutzername für die EC2 Linux-Instanz ec2-user.
** Für AWS und Azure ist das Betriebssystem für das Cloud Manager-Image Red Hat Enterprise Linux 7.4 (HVM).
+
Das Betriebssystem enthält keine GUI. Sie müssen ein Terminal verwenden, um auf das System zuzugreifen.



* Der Installationsordner von Cloud Manager befindet sich am folgenden Speicherort:
+
/opt/application/netapp/cloudmanager

* Protokolldateien befinden sich im folgenden Ordner:
+
/opt/application/netapp/cloudmanager/log

* Der Cloud Manager Service heißt occm.
* Der occm-Dienst ist vom MySQL-Dienst abhängig.
+
Wenn der MySQL-Dienst nicht verfügbar ist, ist auch der occm-Dienst nicht verfügbar.

* Cloud Manager installiert die folgenden Pakete auf dem Linux-Host, sofern sie noch nicht installiert sind:
+
** 7-Zip
** AWSCLI
** Java
** Kubectl
** MySQL
** Tridentctl
** Wget






== Standardkonfiguration für Cloud Volumes ONTAP

Wenn Sie verstehen, wie Cloud Volumes ONTAP standardmäßig konfiguriert ist, können Sie Ihre Systeme einrichten und verwalten. Dies gilt insbesondere, wenn Sie mit ONTAP vertraut sind, da sich das Standard-Setup für Cloud Volumes ONTAP von ONTAP unterscheidet.

* Cloud Volumes ONTAP ist als Single-Node-System und als HA-Paar in AWS und Azure verfügbar.
* Cloud Manager erstellt bei der Implementierung von Cloud Volumes ONTAP eine Data Serving SVM. Sie können zwar über System Manager oder die CLI eine weitere SVM mit Datenbereitstellung erstellen, jedoch wird die Verwendung mehrerer SVMs mit Datenbereitstellung nicht unterstützt.
* Standardmäßig werden mehrere Netzwerkschnittstellen erstellt:
+
** Eine Cluster Management-LIF
** Eine Intercluster-LIF
** Eine Node Management-LIF
** Eine iSCSI-Daten-LIF
** Eine CIFS- und NFS-Daten-LIF
+

NOTE: Aufgrund der EC2-Anforderungen ist das LIF-Failover für Cloud Volumes ONTAP standardmäßig deaktiviert. Durch die Migration einer LIF auf einen anderen Port wird die externe Zuordnung zwischen IP-Adressen und Netzwerkschnittstellen in der Instanz aufgehoben, sodass der LIF nicht mehr zugänglich ist.



* Cloud Volumes ONTAP sendet Konfigurations-Backups über HTTPS an Cloud Manager.
* Wenn Sie sich bei Cloud Manager anmelden, können Sie über die Backup-Daten darauf zugreifen https://[]
* Cloud Manager legt einige Volume-Attribute anders fest als andere Management-Tools (z. B. System Manager oder CLI).
+
In der folgenden Tabelle sind die Volume-Attribute aufgeführt, die Cloud Manager anders als die Standardeinstellungen festlegt:

+
[cols="15,85"]
|===
| Attribut | Vom Cloud Manager festgelegter Wert 


| AutoSize Modus | Wachsen 


| Maximale automatische Größe  a| 
1.000 Prozent


NOTE: Der Cloud Manager Admin kann diesen Wert auf der Seite Einstellungen ändern.



| Sicherheitsstil | NTFS für CIFS-Volumes UNIX für NFS-Volumes 


| Platz garantiert Stil | Keine 


| UNIX-Berechtigungen (nur NFS) | 777 
|===
+
Informationen zu diesen Attributen finden Sie auf der Seite „_Volume create_ man“.





== Boot- und Root-Daten für Cloud Volumes ONTAP

Zusätzlich zum Storage für Benutzerdaten erwirbt Cloud Manager auch Cloud Storage für Boot- und Root-Daten auf jedem Cloud Volumes ONTAP System.



=== AWS

* Eine bereitgestellte IOPS SSD-Festplatte für Cloud Volumes ONTAP Boot-Daten, die ca. 45 GB und 1.250 Piops betragen
* Eine universelle SSD-Festplatte für Cloud Volumes ONTAP Root-Daten mit ca. 140 GB
* Ein EBS-Snapshot für jede Boot- und Root-Festplatte


In einem HA-Paar replizieren beide Cloud Volumes ONTAP Nodes ihre Root-Festplatte auf den Partner-Node.



=== Azure

* Eine Premium Storage SSD-Festplatte für Cloud Volumes ONTAP Bootdaten, die ca. 73 GB betragen
* Eine Premium Storage SSD-Festplatte für Cloud Volumes ONTAP Root-Daten, die ca. 140 GB betragen
* Ein Azure Snapshot für jedes Boot- und Root-Laufwerk




=== Wo sich die Festplatten befinden

Cloud Manager legt den Storage von AWS und Azure wie folgt fest:

* Startdaten befinden sich auf einer Festplatte, die mit der EC2-Instanz oder der Azure Virtual Machine verbunden ist.
+
Diese Festplatte, die das Boot-Image enthält, steht Cloud Volumes ONTAP nicht zur Verfügung.

* Die Stammdaten, die die Systemkonfiguration und die Protokolle enthalten, befinden sich in aggr0.
* Das Root-Volume der Storage Virtual Machine (SVM) befindet sich in aggr1.
* Daten-Volumes befinden sich auch in aggr1.

