---
sidebar: sidebar 
permalink: reference_networking_azure.html 
keywords: networking, network, requirements, connection, connections, vnet, security group, security groups, subnet, vpn, internet, proxy, HTTP, private, proxy server, routing, firewall, autosupport, connection, jump host, outbound, ports, blob, service endpoint 
summary: Sie müssen Ihr Azure Networking so einrichten, dass Cloud Volumes ONTAP Systeme ordnungsgemäß funktionieren. 
---
= Netzwerkanforderungen für Cloud Volumes ONTAP in Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie müssen Ihr Azure Networking so einrichten, dass Cloud Volumes ONTAP Systeme ordnungsgemäß funktionieren.

****
Suchen Sie nach der Liste der Endpunkte, auf die Cloud Manager Zugriff benötigt? Sie werden jetzt an einem einzigen Ort gepflegt. link:reference_networking_cloud_manager.html["Details finden Sie hier"].

****
Outbound-Internetzugang für Cloud Volumes ONTAP:: Cloud Volumes ONTAP erfordert ausgehenden Internetzugang, um Nachrichten an NetApp AutoSupport zu senden, der proaktiv den Zustand Ihres Storage überwacht.
+
--
Routing- und Firewall-Richtlinien müssen AWS HTTP-/HTTPS-Datenverkehr an die folgenden Endpunkte ermöglichen, damit Cloud Volumes ONTAP AutoSupport-Meldungen senden kann:

* \https://support.netapp.com/aods/asupmessage
* \https://support.netapp.com/asupprod/post/1.0/postAsup


--
Sicherheitsgruppen:: Sie müssen keine Sicherheitsgruppen erstellen, da Cloud Manager dies für Sie tut. Wenn Sie Ihr eigenes verwenden müssen, lesen Sie link:reference_security_groups_azure.html["Regeln für Sicherheitsgruppen"].
Verbindung von Cloud Volumes ONTAP zu Azure Blob Storage für Data Tiering:: Wenn Sie „kalte“ Daten für Azure Blob Storage Tiering möchten, müssen Sie keinen vnet Service-Endpunkt einrichten, wenn Cloud Manager über die erforderlichen Berechtigungen verfügt:
+
--
[source, json]
----
"Microsoft.Network/virtualNetworks/subnets/write",
"Microsoft.Network/routeTables/join/action",
----
Diese Berechtigungen sind in der neuesten enthalten https://["Cloud Manager-Richtlinie"].

Weitere Informationen zum Einrichten von Daten-Tiering finden Sie unter link:task_tiering.html["Tiering von kalten Daten auf kostengünstigen Objekt-Storage"].

--
Verbindungen zu ONTAP Systemen in anderen Netzwerken:: Um Daten zwischen einem Cloud Volumes ONTAP System in Azure und ONTAP Systemen in anderen Netzwerken zu replizieren, müssen Sie über eine VPN-Verbindung zwischen Azure VNet und dem anderen Netzwerk verfügen, z. B. einem AWS VPC oder Ihrem Unternehmensnetzwerk.
+
--
Anweisungen finden Sie unter https://["Microsoft Azure Dokumentation: Erstellen Sie eine Site-to-Site-Verbindung im Azure-Portal"^].

--

