---
pagenav: false 
sidebar: sidebar 
permalink: task_getting_started_aws.html 
keywords: amazon web services, aws, netapp, data fabric, hybrid cloud, cloud, public cloud, networking, vpc, quick, getting started, install, installing, deploy, deploying, setup, setting up, launching, requirements, prerequisites, cloud central, get started, network, vpn, multi-cloud, tier, tiering, storage tier, data tier, vpc endpoint, endpoint, S3, subscribe, subscribing, marketplace, granting, permissions, policy, iam policy, ec2 console, ami, mediator, connectivity, internet, outbound, endpoint, connection, networks, replicating, ec2 service, policies, attach, iam user, access key, secret key, keys, sign up, cloud manager, cloud volumes ontap, cloud ontap, create 
summary: Sie können mit Cloud Volumes ONTAP in AWS beginnen, indem Sie einige kurze Schritte ausführen. 
---
= Erste Schritte mit Cloud Volumes ONTAP in AWS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Die ersten Schritte mit Cloud Volumes ONTAP in AWS sind über NetApp Cloud Central möglich.



=== Richten Sie Ihr Netzwerk ein

. Aktivieren Sie ausgehenden Internetzugriff vom Ziel-VPC aus, sodass Cloud Manager und Cloud Volumes ONTAP mit mehreren Endpunkten in Verbindung treten können.
+
Dieser Schritt ist wichtig, da Cloud Manager Cloud Volumes ONTAP nicht ohne ausgehenden Internetzugang implementieren kann. Wenn Sie die ausgehende Verbindung begrenzen müssen, lesen Sie die Liste der Endpunkte für link:reference_networking_cloud_manager.html#outbound-internet-access["Cloud Manager"] Und link:reference_networking_aws.html#general-aws-networking-requirements-for-cloud-volumes-ontap["Cloud Volumes ONTAP"].

. Richten Sie einen VPC-Endpunkt für den S3-Dienst ein.
+
Ein VPC-Endpunkt ist erforderlich, wenn Sie kalte Daten von Cloud Volumes ONTAP auf kostengünstigen Objekt-Storage einstufen möchten.





=== Abonnieren Sie Cloud Volumes ONTAP über den AWS Marketplace

[role="quick-margin-para"]
Abonnieren von https://aws.amazon.com/marketplace/search/results?page=1&searchTerms=netapp+cloud+volumes+ontap["AWS Marketplace"^] Ist zur Annahme der Softwarebedingungen erforderlich. Sie sollten sich nur über Marketplace anmelden. Starten von Cloud Volumes ONTAP von überall aus, Cloud Manager wird jedoch nicht unterstützt.



=== Stellen Sie die erforderlichen AWS-Berechtigungen bereit

[role="quick-margin-para"]
Wenn Sie Cloud Manager über NetApp Cloud Central implementieren, müssen Sie ein AWS-Konto verwenden, das über die Berechtigung zum Bereitstellen der Instanz verfügt.

. Gehen Sie zur AWS IAM-Konsole und erstellen Sie eine Richtlinie durch Kopieren und Einfügen der Inhalte des https://mysupport.netapp.com/cloudontap/iampolicies["NetApp Cloud Central-Richtlinie für AWS"^].
. Hängen Sie die Richtlinie an den IAM-Benutzer an.




=== Starten Sie Cloud Manager über NetApp Cloud Central

[role="quick-margin-para"]
Cloud Manager Software ist für die Implementierung und das Management von Cloud Volumes ONTAP erforderlich. Es dauert nur ein paar Minuten, um eine Cloud Manager Instanz von zu starten https://cloud.netapp.com["Cloud Central"^].



=== Starten Sie Cloud Volumes ONTAP mit Cloud Manager

[role="quick-margin-para"]
Wenn Cloud Manager fertig ist, klicken Sie einfach auf Erstellen, wählen Sie den Systemtyp aus, den Sie starten möchten, und führen Sie die Schritte im Assistenten aus. Nach 25 Minuten sollte Ihr erstes Cloud Volumes ONTAP System betriebsbereit sein.

.Weiterführende Links
* link:concept_evaluating.html["Bewertung"]
* link:reference_networking_cloud_manager.html["Netzwerkanforderungen für Cloud Manager"]
* link:reference_networking_aws.html["Netzwerkanforderungen für Cloud Volumes ONTAP in AWS"]
* link:reference_security_groups.html["Sicherheitsgruppenregeln für AWS"]
* link:task_adding_cloud_accounts.html["Cloud Provider Accounts zu Cloud Manager hinzufügen"]
* link:reference_permissions.html#what-cloud-manager-does-with-aws-permissions["Was Cloud Manager mit AWS-Berechtigungen macht"]
* link:task_deploying_otc_aws.html["Starten von Cloud Volumes ONTAP in AWS"]
* link:task_launching_aws_mktp.html["Starten von Cloud Manager über den AWS Marketplace"]

