---
sidebar: sidebar 
permalink: task_installing_linux.html 
keywords: install, installation, installing, linux, installer, software, on prem, on-prem, silent 
summary: Die geläufigste Methode für die Implementierung von Cloud Manager besteht aus Cloud Central oder aus dem Markt eines Cloud-Providers. Sie haben jedoch die Möglichkeit, die Cloud Manager-Software auf einem vorhandenen Linux-Host in Ihrem Netzwerk oder in der Cloud herunterzuladen und zu installieren. 
---
= Installieren von Cloud Manager auf einem vorhandenen Linux-Host
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Die geläufigste Methode für die Implementierung von Cloud Manager besteht aus Cloud Central oder aus dem Markt eines Cloud-Providers. Sie haben jedoch die Möglichkeit, die Cloud Manager-Software auf einem vorhandenen Linux-Host in Ihrem Netzwerk oder in der Cloud herunterzuladen und zu installieren.

.Bevor Sie beginnen
* Ein Red Hat Enterprise Linux-System muss bei Red Hat Subscription Management registriert sein. Wenn sie nicht registriert ist, kann das System während der Cloud Manager-Installation nicht auf Repositorys zugreifen, um die erforderliche Software von Drittanbietern zu aktualisieren.
* Das Cloud Manager-Installationsprogramm greift während des Installationsvorgangs auf mehrere URLs zu. Sie müssen sicherstellen, dass ausgehende Internetzugriffe auf diese Endpunkte zulässig sind. Siehe link:reference_networking_cloud_manager.html["Netzwerkanforderungen für Cloud Manager"].


.Über diese Aufgabe
* Für die Installation von Cloud Manager sind keine Root-Berechtigungen erforderlich.
* Cloud Manager installiert die AWS-Befehlszeilentools (awscli), um Recovery-Verfahren vom NetApp Support zu ermöglichen.
+
Wenn Sie eine Meldung erhalten, dass die Installation des awscli fehlgeschlagen ist, können Sie die Meldung ignorieren. Cloud Manager kann ohne die Tools erfolgreich arbeiten.

* Das Installationsprogramm, das auf der NetApp Support-Website verfügbar ist, kann möglicherweise eine frühere Version sein. Nach der Installation aktualisiert sich Cloud Manager automatisch, wenn eine neue Version verfügbar ist.


.Schritte
. Netzwerkanforderungen prüfen:
+
** link:reference_networking_cloud_manager.html["Netzwerkanforderungen für Cloud Manager"]
** link:reference_networking_aws.html["Netzwerkanforderungen für Cloud Volumes ONTAP für AWS"]
** link:reference_networking_azure.html["Netzwerkanforderungen für Cloud Volumes ONTAP für Azure"]


. Prüfen link:reference_cloud_mgr_reqs.html["Anforderungen an den Cloud Manager Host"].
. Laden Sie die Software von herunter http://mysupport.netapp.com/NOW/cgi-bin/software["NetApp Support Website"^], Und dann kopieren Sie es auf den Linux-Host.
+
Informationen zum Verbinden und Kopieren der Datei auf eine EC2-Instanz in AWS finden Sie unter http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AccessingInstancesLinux.html["AWS Documentation: Herstellen einer Verbindung zu Ihrer Linux-Instanz mithilfe von SSH"^].

. Weisen Sie Berechtigungen zum Ausführen des Skripts zu.
+
*Beispiel*

+
 chmod +x OnCommandCloudManager-V3.6.3.sh
. Führen Sie das Installationsskript aus:
+
 ./OnCommandCloudManager-V3.6.3.sh [silent] [proxy=ipaddress] [proxyport=port] [proxyuser=user_name] [proxypwd=password]
+
_Silent_ führt die Installation aus, ohne dass Sie zur Information aufgefordert werden.

+
_Proxy_ ist erforderlich, wenn sich der Cloud Manager-Host hinter einem Proxy-Server befindet.

+
_proxyport_ ist der Port für den Proxy-Server.

+
_Proxyuser_ ist der Benutzername für den Proxy-Server, wenn eine grundlegende Authentifizierung erforderlich ist.

+
_Proxypwd_ ist das Passwort für den von Ihnen angegebenen Benutzernamen.

. Wenn Sie den Silent-Parameter nicht angegeben haben, geben Sie *Y* ein, um das Skript fortzusetzen, und geben Sie anschließend die HTTP- und HTTPS-Ports ein, wenn Sie dazu aufgefordert werden.
+
Wenn Sie die HTTP- und HTTPS-Ports ändern, müssen Sie sicherstellen, dass Benutzer von einem Remote-Host aus auf die Cloud Manager-Webkonsole zugreifen können:

+
** Ändern Sie die Sicherheitsgruppe, um eingehende Verbindungen über die Ports zuzulassen.
** Geben Sie den Port an, wenn Sie die URL für die Cloud Manager-Webkonsole eingeben.
+
Cloud Manager ist jetzt installiert. Nach Abschluss der Installation wird der Cloud Manager-Dienst (occm) zweimal neu gestartet, wenn Sie einen Proxyserver angegeben haben.



. Öffnen Sie einen Webbrowser, und geben Sie die folgende URL ein:
+
https://_ipaddress_:__port__[]

+
_Ipaddress_ kann abhängig von der Konfiguration des Cloud Manager-Hosts localhost, eine private IP-Adresse oder eine öffentliche IP-Adresse sein. Wenn sich Cloud Manager beispielsweise in der Public Cloud ohne öffentliche IP-Adresse befindet, müssen Sie eine private IP-Adresse von einem Host eingeben, der eine Verbindung zum Cloud Manager-Host hat.

+
_Port_ ist erforderlich, wenn Sie die Standard-HTTP (80)- oder HTTPS (443)-Ports geändert haben. Wenn beispielsweise der HTTPS-Port in 8443 geändert wurde, würden Sie eingeben https://_ipaddress_:8443[]

. Melden Sie sich für ein NetApp Cloud Central Konto an, oder melden Sie sich an, wenn Sie bereits über ein Konto verfügen.
. Wenn Sie sich anmelden oder anmelden, fügt Cloud Manager Ihr Benutzerkonto automatisch als Administrator für dieses System hinzu.
. Geben Sie nach der Anmeldung einen Namen für dieses Cloud Manager-System ein.


.Nachdem Sie fertig sind
Richten Sie Berechtigungen für Ihre AWS und Azure Konten ein, damit Cloud Manager Cloud Volumes ONTAP implementieren kann:

* Wenn Sie Cloud Volumes ONTAP in AWS implementieren möchten, link:task_adding_cloud_accounts.html["AWS Konto einrichten und dann zu Cloud Manager hinzufügen"].
* Wenn Sie Cloud Volumes ONTAP in Azure implementieren möchten, link:task_adding_cloud_accounts.html#setting-up-and-adding-azure-accounts-to-cloud-manager["Richten Sie ein Azure-Konto ein, und fügen Sie es anschließend zu Cloud Manager hinzu"].

